import type { PR } from "@/components/pr-table"

export const mockPRs: PR[] = [
  {
    id: "pr_101",
    title: "feat: streaming micro-payment engine and settlement hooks",
    description:
      "Implements real-time payout calculation for contributors and settlement hooks for on-chain mint flow.",
    score: 92,
    amountEarned: 1543.25,
    currency: "₹",
    status: "streaming",
    ratePerSec: 0.03,
    linkedIssue: "https://github.com/org/repo/issues/342",
    linesAdded: 1240,
    linesDeleted: 310,
    coverage: 87,
    merged: false,
    approvals: 2,
    scoreBreakdown: [
      { label: "Tests", value: 20 },
      { label: "Linked Issue", value: 20 },
      { label: "Documentation", value: 12 },
      { label: "Complexity Reduction", value: 25 },
      { label: "Code Quality", value: 15 },
    ],
  },
  {
    id: "pr_102",
    title: "chore(ci): add test matrix, caching, and slack notifications",
    description: "Improves CI throughput and adds notifications. Includes cache busting strategy for flaky runners.",
    score: 78,
    amountEarned: 720.0,
    currency: "₹",
    status: "paid",
    linkedIssue: null,
    linesAdded: 210,
    linesDeleted: 57,
    coverage: 75,
    merged: true,
    approvals: 1,
    scoreBreakdown: [
      { label: "Tests", value: 15 },
      { label: "Linked Issue", value: 0 },
      { label: "Documentation", value: 8 },
      { label: "Complexity Reduction", value: 30 },
      { label: "Code Quality", value: 25 },
    ],
  },
  {
    id: "pr_103",
    title: "fix: address race condition in stream reconciler",
    description: "Fixes a race condition during ledger compaction; adds safe guards and retries with jitter.",
    score: 88,
    amountEarned: 980.5,
    currency: "₹",
    status: "streaming",
    ratePerSec: 0.02,
    linkedIssue: "https://github.com/org/repo/issues/367",
    linesAdded: 120,
    linesDeleted: 45,
    coverage: 82,
    merged: false,
    approvals: 3,
    scoreBreakdown: [
      { label: "Tests", value: 18 },
      { label: "Linked Issue", value: 20 },
      { label: "Documentation", value: 10 },
      { label: "Complexity Reduction", value: 20 },
      { label: "Code Quality", value: 20 },
    ],
  },
]
